### ISSUE TITLE
Bar Plot issues

### ISSUE THREAD

**Issue by PradeepGaneshbabu** [pyviz/hvplot#229] opened 2019-06-26 07:18 UTC
I need the bar plot to be same as what I get from pandas

Pandas plot image:

![image](https://user-images.githubusercontent.com/47116729/60159182-7df43600-97a7-11e9-8cf1-fe716ee2d8b9.png)

Dataframe image: 

![image](https://user-images.githubusercontent.com/47116729/60159250-9f552200-97a7-11e9-8561-09ca6c2b13a6.png)

What I get from hvplot - saving as html

![image](https://user-images.githubusercontent.com/47116729/60159022-1ccc6280-97a7-11e9-80ab-fbce5381b44c.png)

I need to move <80% to the left most, I am not able to change ylim even though I give a tuple as params, would love to select ea or ca from legend and need to change order of EA and CA bar. Need to show EA first then CA. 

My current plot code:

    hvplot.save((df_counts.hvplot.bar(y = ['EA','CA'], ylim = (0, 1.2 * df_counts.max().max()), width=1000, height=500, title='Availability_' + str(month_name[int(month)]), ylabel='Count of sites' , xlabel='Availability')), 'Bar1.html')

Could someone help me correct this?

The whole reason why I want to use hvplot is because of the dynamic plot and not static plots like pandas.

**Comment by jsignell** [comment] 2019-07-17 15:29
Even simpler example:

![2019-07-16](https://user-images.githubusercontent.com/4806877/61388900-08e7be00-a886-11e9-9782-448124e46797.png)

default seems to be sorting alphabetically

**Comment by philippjfr** [comment] 2019-07-17 15:38
Duplicate of https://github.com/pyviz/hvplot/issues/208

**Closed by philippjfr** 2019-07-17 15:38 UTC
Labels: type: bug
