### ISSUE TITLE
Incorrect param warning on bar plot + width

### ISSUE THREAD

**Issue by jsignell** [pyviz/hvplot#283] opened 2019-08-08 13:59 UTC
There is a new param warning that feels incorrect:

`WARNING:param.BarPlot02810: BarPlot width option is deprecated use 'bar_width' instead.`

<img width="1010" alt="Screen Shot 2019-08-08 at 9 57 27 AM" src="https://user-images.githubusercontent.com/4806877/62709258-0418b480-b9c3-11e9-985d-67eebb658669.png">

**Comment by philippjfr** [comment] 2019-08-08 14:10
The warning is correct, the problem is likely that the option is being set as a style option rather than a plot option. Did we switch to the new style merged .opts anywhere?

**Comment by philippjfr** [comment] 2019-08-08 14:11
Actually even with the new style, merged options plot options should take precedence over style options. Is it possible that width is ending up in the style options inside hvplot somehow?

**Comment by jsignell** [comment] 2019-08-08 14:12
I have a fix.

**Closed** 2019-08-08 15:23 UTC
Labels: status: ready, type: bug
